# Generated by Django 6.0.3 on 2026-04-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="profile.jpg", upload_to="profile_pics"),
        ),
    ]
